# Generated by Django 6.0.5 on 2026-05-22 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
                ('partidas_jugadas', models.PositiveIntegerField(default=0)),
                ('partidas_ganadas', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando Jugadores'), ('en_ronda', 'En Ronda Activa'), ('evaluacion', 'En Votación'), ('terminada', 'Partida Terminada')], default='esperando', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_creadas', to='juego.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ronda', models.IntegerField()),
                ('letra', models.CharField(max_length=1)),
                ('activa', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='juego.sala')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('ciudad_pais', models.CharField(blank=True, default='', max_length=100)),
                ('animal', models.CharField(blank=True, default='', max_length=100)),
                ('cosa', models.CharField(blank=True, default='', max_length=100)),
                ('puntos_nombre', models.IntegerField(default=0)),
                ('puntos_apellido', models.IntegerField(default=0)),
                ('puntos_ciudad_pais', models.IntegerField(default=0)),
                ('puntos_animal', models.IntegerField(default=0)),
                ('puntos_cosa', models.IntegerField(default=0)),
                ('total_puntos_ronda', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_juego', to='juego.perfilusuario')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='juego.ronda')),
            ],
            options={
                'unique_together': {('ronda', 'jugador')},
            },
        ),
    ]
