# Generated by Django 6.0.5 on 2026-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestajugador',
            options={'ordering': ['-ronda__numero_ronda']},
        ),
        migrations.AlterModelOptions(
            name='ronda',
            options={'ordering': ['numero_ronda']},
        ),
        migrations.AlterUniqueTogether(
            name='respuestajugador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='puntaje_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ronda',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='numero_ronda',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('esperando', 'Esperando Jugadores'), ('en_ronda', 'En Ronda Activa'), ('cuenta_regresiva', 'Cuenta Regresiva (10s)'), ('evaluacion', 'Calculando Puntos'), ('terminada', 'Partida Terminada')], default='esperando', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='respuestajugador',
            constraint=models.UniqueConstraint(fields=('ronda', 'jugador'), name='unique_respuesta_por_ronda'),
        ),
    ]
