# Generated by Django 6.0.5 on 2026-05-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_alter_respuestajugador_options_alter_ronda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_unido', models.DateTimeField(auto_now_add=True)),
                ('listo', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='juego.perfilusuario')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='juego.sala')),
            ],
            options={
                'ordering': ['fecha_unido'],
                'unique_together': {('sala', 'jugador')},
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='jugadores',
            field=models.ManyToManyField(related_name='salas_participadas', through='juego.SalaJugador', to='juego.perfilusuario'),
        ),
    ]
