# Generated by Django 6.0.5 on 2026-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_salajugador_sala_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='modo_juego',
            field=models.CharField(choices=[('clasico', 'Modo Clásico'), ('alcoholico', 'Modo Alcohólico')], default='clasico', max_length=20),
        ),
    ]
