# Generated by Django 6.0.5 on 2026-06-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_sala_modo_juego'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial del Clan', max_length=50, unique=True)),
                ('tag', models.CharField(help_text='Etiqueta corta, ej: [ZTOP]', max_length=5, unique=True)),
                ('limite_miembros', models.IntegerField(default=15, help_text='Capacidad máxima de jugadores')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('chat_sala', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan_asociado', to='social.grupochat')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clanes_liderados', to='juego.perfilusuario')),
                ('miembros', models.ManyToManyField(blank=True, related_name='clanes_unidos', to='juego.perfilusuario')),
            ],
        ),
    ]
