# Generated by Django 6.0.5 on 2026-06-15 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juego', '0004_sala_modo_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCosmetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('seed', models.CharField(help_text='La semilla de DiceBear', max_length=100)),
                ('categoria', models.CharField(choices=[('bottts', 'Robots (Bottts)'), ('pixel-art', 'Pixel Art'), ('avataaars', 'Personas (Avataaars)'), ('monsters', 'Monstruos')], default='bottts', max_length=20)),
                ('precio', models.IntegerField(default=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioCosmetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='juego.perfilusuario')),
                ('items_desbloqueados', models.ManyToManyField(blank=True, to='tienda.itemcosmetico')),
            ],
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monedas', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monedero', to='juego.perfilusuario')),
            ],
        ),
    ]
