# Generated by Django 6.0.5 on 2026-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcosmetico',
            name='nivel_requerido',
            field=models.IntegerField(default=1, help_text='Nivel mínimo para desbloquearlo gratis (1, 5, 10, 15...)'),
        ),
        migrations.AlterField(
            model_name='itemcosmetico',
            name='precio',
            field=models.IntegerField(default=100, help_text='Precio en monedas. 0 si es exclusivo por nivel.'),
        ),
    ]
