# Generated by Django 6.0.5 on 2026-06-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_itemcosmetico_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcosmetico',
            name='categoria',
            field=models.CharField(choices=[('bottts', 'Robots (Bottts)'), ('pixel-art', 'Pixel Art'), ('avataaars', 'Personas (Avataaars)'), ('fun-emoji', 'Emojis Divertidos'), ('minecraft', 'Minecraft (Ultra VIP)')], default='bottts', max_length=20),
        ),
    ]
